language: generic
dist: xenial
sudo: required
install:
- bash scripts/travis_provision.sh
before_script:
- go build main.go
script:
- bash test.sh
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: riaExw87WY0LLjHbvA7qGml9ahljEXv1Qkm0TVeyzvGKWNOGYvwTeg+6sLI1HbEV68ECqk6DkJOT5jawYt75ZN+EAX7fW0v0AWvGdeAHZl6ln6GrD+hXzvawAyd8NyuKsA+dCy177Wr5sHnXh0G/qlSDw9tyfyzZu7cW8HUmHdcobNtfueN9C/wVIqYxMYGG5dkhZEd5lQakWCRNxBRL2frupZVheN7BcUbExjAmzX+uYmile2+lqC6Am+C0XThQiL+ucsaYtMgBE3hSNLlt0vUps1GVmkp63D/D/WkrJF7cKaMJqCG2Khkk/zpJDx9BdKxahYxNw7EiD75CRL4E3ps3r1pQY93gzaZv1A1++Ozvgax4qGIuW7lU6Lt57uyJwzl1L3WRzfXhAg7x2VyBX76tYlv2MsQFnF1+FbFiZKe74iu3RCU5L9izgY/57gt4vrQHPJNoUr/fbvBVutLquTDqskAXk1RAeojiNgB2uTwEYNBvFhlEOOh7MNb1sPkjGU3yP9x7yDMg8wNe2gTlZdbtdHOg7gttsgGplu/RrlFmUSkq97i4Xy5ALCafmlBmhfcV+AQ6I+j6jy1ouUVfauLUdtLRh7Ejb9vMMmCMa7K/bNSxjEygDReB5gfJVrVjZ4JUiGz5pyLQI1NsNlR/z+oyFi5BtOUav/TGRGcTxGE=
  file: main
  on:
    repo: berchev/golang_hello
    tags: true