language: generic
dist: xenial
sudo: required
install:
- while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
- bash scripts/travis_provision.sh
before_script:
- go build main.go
script:
- bash test.sh
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: DIGnsBNOjsF0skez5jgqHW8shGdr0HZMlPxEmWR1RUq8zwPq6NNSjENjsSUc7gtGfPK76eMTj3ZS0VT35w6iQpl+NIROuTyXKm6xY6O4ulv9uGdOsreOmYFqQM0jwgH6DMAxohj6j8KvNwjBCMst2vJWgJJm+Z+HmI+y6Tz4hfnzwX+rvAU4ndnMhPAINWQp2Kjt6rbyhxLSzx02p+ipAcHYm984h+7+tyWRAiRfuJ0YI5VuyzqDksnJO08E+MHnORfDW9tdeMdtrJN1LZi78YiEoV7gb1/kd6KwrfA7jgvGUrhpM/9IxUo8xou3MxfTajgz0uHCLy7SjJtYTMW+l+DNuRpjTz92aXR6PB+ukFtrA5membKt6NrvuuAk6t1zdZdT6dn/fMeDTRWOg0/easU0X0z2TK/CQwhaspgVcirdh0fq08xfqARZfqG2H5Bjw51ZfQlWmzZJEWPw3MldWzN0SoWHcwimkH0qQ3ex2valXwM6oZ2aR+B+30fwRceG6UeoqZlE5ShvLjLrtCFyzW/gnCqzsR2qOecLVaGmikN3qHLFWRj4fzWkIIdfAiCKVE5Ixf90e7Voubi82Nw8mhenZe3q9hwXtTFcSvvDNC3eTqaLtep/Fk7XESAD9CVRMTCD6kVKo3n9ngnnrwosHiWorioPYFEyU+AUaOZQEF4=
  file: main
  on:
    repo: berchev/golang_hello
    tags: true