language: generic
dist: xenial
sudo: required
install:
- bash scripts/travis_provision.sh
script:
- bash test.sh
deploy:
  provider: releases
  api_key:
    secure: J9k4cxhbDsAGT83gZ4gWb3ezHwUubqsm3yL3oIa/udGQGLRXBIlmN1Zl6t404NOHaHN7EmbNs9k8S3ehWoYLH+p685NjK6O5m7p21VJ9gMbtzcQFmlQ/45efweEMCHjug8mTnQE8zAr+4LfM4UVNzyL2W5TMznws4qQU1LB8l2tOlapaM2AM16itVabgFGOlu/jO0J4YVO5G1SW0f7JmV6sOfQ/uJaAUJTE+/+uw+5Y6eo/HHZ0d5hkeqZcUzR35Ci3z8BB3PKF/KT/pPhBe4WIpfKwKL8nXDQMF/Kf551gx4NaQvFOFiea90JzTrn8O5QGCP+HsYhUzwGeksw8NTIm1JGuNnPnHF1hNgxSwA/T0rAZKAN7LunauMI3L/M7KuwQU9WL6lcBZ4yniYUaVIBbDHCKRoj9AODmB6TYlDPJgl8TSGrgsFnz10h51KLhWogVkpyAwNuHm7pwiizu+icfR2QRN4MiXh+HTvH0nZVdllxVLdo/ws/NI7UprAa3sSP03niOYWVWzYHXDqceAcF3l9C5sr98i2IcjqSUIYdVJiqMb32xFAjYjJ2/rr2QDHR/UkbqN/CPNKSSRn8FOqLNmgChTKVg0+TXo1D5rxVCDQ9MzjL9cKuFl4QdVvzV4jpzrL/634rPjbpcUlQ71XrBBheaDBq91N0McXTTQmc0=
  file: main.go
  on:
    repo: berchev/golang_hello
    tags: true