language: generic
dist: xenial
sudo: required
install:
- bash scripts/travis_provision.sh
script:
- bash test.sh
deploy:
  provider: releases
  api_key:
    secure: nbvyWrpJ2HPxyxMSB3vENVaifmEnnhmvfdAJ8BsceLyEK1nwiDEpV2ujUCzMahGK0xm4kG2JvXyqUzorct8xiRHQT/cyBXN1mdmDZEAwQQZovkU5EBsLzPkZEO0SZxfqKbHNyWEN5BJBO+aA+KiuLgXdH7f911tiOobKrl7zwcpIsiXggTRM14tB868PBFoTll1awL24JVVnWTVsXOujbaprA/Ehrr77Nll5LNp31IXSD+aTK9irAwX2YvQd8SxyeiavhiBoupxiTck4z1oxBI6fALdJeEdbbV0mtg+JMc/iYToBBFjq65TUf0HADCpKnDxHBmTQefmwD2HquABlOQ8HY7X8mDHSeh54F6vg56zTYV2ZIbsV6/8PWErfjjQip35UHLbqG/8YPE2PIOr7oN7j2lVUJNwuHu7cLOaun7IOD1pEUDOC6qCCdnjtH+IWiVT2Lpclp0zdgOKWFGIXOY4pF87x7NQPj/bmbyC+bVF8kL2n3pbIInBF46CfjP9MCLaoCr/rG+t2P2KeE2juc+/8sk/2CuTsMdlrnH6yZLBeo4BY66OXA7p7TlMVHb8ocd2Qw4WszJopwwES+imP0kU8K5oThJFJqZJqg9GM0l8FehXHbQT9dvSMo0ModTRhXYv8ZZFGh6WXumcxA0WHcTVhtw+pocWms0cAmEibY+c=
  file: main.go
  on:
    repo: berchev/golang_hello
    tag: true